app = "new-backend"

primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  SPRING_DATASOURCE_URL = "jdbc:mysql://ballast.proxy.rlwy.net:14117/railway"
  SPRING_DATASOURCE_USERNAME = "root"
  SPRING_DATASOURCE_PASSWORD = "oBDdBeenOLknNaVkYNnWkUPJdSvxsOpn"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
