app = "new-backend"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  # Optional: set your Spring profile
  SPRING_PROFILES_ACTIVE = "prod"

[deploy]
  release_command = "./mvnw fly:deploy"  # optional, you can leave empty if no release steps

[experimental]
  allowed_public_ports = [8080]
