app = "new-backend"  # Your Fly.io app name

[build]
  dockerfile = "Dockerfile"   # Explicitly tell Fly.io to use your Dockerfile

[env]
  # Optional: any environment variables for your Spring Boot app
  SPRING_PROFILES_ACTIVE = "prod"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
