app = "new-tuition-akhl3a"

[build]
# Tells Fly.io to build using Dockerfile in current folder
image = "Dockerfile"

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
port = 80

[[services.ports]]
port = 443
